server:
  port: 8080
spring:
  application:
    name: star-wars-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/db-star-wars
      auto-index-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    uuid-representation: standard

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG

# API URL
apistarwars:
  urlApi: https://swapi.dev/api/
