server:
  port: 8082
spring:
  application:
    name: star-wars-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/db-star-wars
      auto-index-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

# API URL
apistarwars:
  urlApi: https://swapi.dev/api/planets/

# mongodb://localhost:27017/
# mongodb://root:admin@localhost:27017/db-star-wars
