version: "3"
services:
  star-wars-db:
    image: mongo:latest
    container_name: star-wars-db
    restart: always
    environment:
      - MONGODB_USER=root
      - MONGODB_DATABASE=db_star_wars
      - MONGODB_PASS=root
    ports:
      - "27017:27017"